#!/bin/bash
## This file is specific to this project and assumes the shell is
## bash
export PROJ_DIR=`pwd`

alias cdp="cd $PROJ_DIR"
alias cdm="cd $PROJ_DIR/matlab/wk"
alias cdc="cd $PROJ_DIR/cuda/wk"
alias cdps="cd $PROJ_DIR/standards/G729AnexC_float/software"
